# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login-form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 380, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:rgba(16,16,16,255);\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 220, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 270, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(10, 320, 361, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("QPushButton#b1{\n"
"background-color:rgb(249,19,35);\n"
"color:rgb(135,60,0);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#b1:hover{\n"
"background-color:rgb(255,255,255);\n"
"}")
        self.b1.setObjectName("b1")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,191,16);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(260, 0, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255,191,16);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(130, 100, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255,191,16);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(130, 360, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255,255,255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.b2 = QtWidgets.QPushButton(self.widget)
        self.b2.setGeometry(QtCore.QRect(10, 390, 361, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("QPushButton#b2{\n"
"background-color:rgb(249,19,35);\n"
"color:rgb(135,60,0);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#b2:hover{\n"
"background-color:rgb(255,255,255);\n"
"}")
        self.b2.setObjectName("b2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter the username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Enter the password"))
        self.b1.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "🐶"))
        self.label_4.setText(_translate("Form", "🐶"))
        self.label_5.setText(_translate("Form", "🐱"))
        self.label_6.setText(_translate("Form", "New User? Sign Up!!!"))
        self.b2.setText(_translate("Form", "Sign Up"))


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 500))  # Set widget to cover the entire form
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:rgba(16,16,16,255);\n"
                                  "border-radius:20px;")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 220, 380, 40))  # Adjusted width
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        # Remaining code unchanged...

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # Remaining code unchanged...

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    Form.move(QtWidgets.QApplication.desktop().screen().rect().center() - Form.rect().center())  # Center the form
    sys.exit(app.exec_())
